[package]
name = "guavagrams"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
csv = "1.3.1"
itertools = "0.14.0"
rand = "0.9.0"
ratatui = "0.29.0"
thiserror = "2.0.11"
walkdir = "2.5.0"

[profile.release]
codegen-units = 1